### ISSUE TITLE
Also support Kotlin ? 

### ISSUE THREAD

**Issue by burkaslarry** [wonderkiln/CameraKit-Android#243]
I have found this fascinating if using Java for android native apps development. But what if we develop apps with Kotlin ?

**Comment by austinkettner** [comment]
Hey @burkaslarry since Kotlin is fully interop, CameraKit should work in Kotlin without issue! Do you run into issues?

**Comment by iftekhar-ahmed** [comment]
I ran into this absurd issue trynna upgrade to version 0.12.x. After a full build I get hundreds of previously nonexistent nullability errors in all my kotlin files. This happens only for this particular library (and versions > 0.11.0) when added as gradle library dependency. Would appreciate if anyone comes up with a clue or faced similar problems.

**Comment by burkaslarry** [comment]
what if 1.2.0 ?

**Comment by austinkettner** [comment]
@iftekhar-ahmed Can you outline what version of Kotlin and some example errors?

**Comment by burkaslarry** [comment]
I have used kotlin 1.2.0  . seems ok .could you please tell me ....any examples of using captureImage with completion handler  ?

**Comment by burkaslarry** [comment]
I have sen the doc , no page for mentioning this.

**Comment by iftekhar-ahmed** [comment]
@austinkettner I tried kotlin **1.1.60**. Here is sample build errors -

library version - **0.12.1**

`e: /Workspace/tise-android/app/src/main/java/com/tise/tise/adapters/AbsFragmentPagerAdapter.kt: (29, 5): 'destroyItem' overrides nothing
e: /Workspace/tise-android/app/src/main/java/com/tise/tise/adapters/AbsFragmentPagerAdapter.kt: (31, 27): Type mismatch: inferred type is ViewGroup? but ViewGroup was expected
e: /Workspace/tise-android/app/src/main/java/com/tise/tise/fragments/AddToUDLDialogFragment.kt: (119, 68): Type mismatch: inferred type is Context? but Context was expected
e: /Workspace/tise-android/app/src/main/java/com/tise/tise/fragments/AddToUDLDialogFragment.kt: (121, 53): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type FragmentActivity?
e: /Workspace/tise-android/app/src/main/java/com/tise/tise/fragments/AddToUDLDialogFragment.kt: (137, 64): Type mismatch: inferred type is Context? but Context was expected
e: /Workspace/tise-android/app/src/main/java/com/tise/tise/fragments/AddToUDLDialogFragment.kt: (139, 49): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type FragmentActivity?
e: /Workspace/tise-android/app/src/main/java/com/tise/tise/fragments/AddToUDLDialogFragment.kt: (161, 52): Type mismatch: inferred type is Context? but Context was expected
e: /Workspace/tise-android/app/src/main/java/com/tise/tise/fragments/AddToUDLDialogFragment.kt: (163, 37): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type FragmentActivity?
e: /Workspace/tise-android/app/src/main/java/com/tise/tise/fragments/AddToUDLDialogFragment.kt: (186, 27): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type Bundle?
e: /Workspace/tise-android/app/src/main/java/com/tise/tise/fragments/AddToUDLDialogFragment.kt: (187, 27): Smart cast to 'AppCompatActivity' is impossible, because 'activity' is a property that has open or custom getter
e: /Workspace/tise-android/app/src/main/java/com/tise/tise/fragments/AddToUDLDialogFragment.kt: (216, 43): Type mismatch: inferred type is Context? but Context was expected
e: /Workspace/tise-android/app/src/main/java/com/tise/tise/fragments/AddToUDLDialogFragment.kt: (227, 5): 'onCreateView' overrides nothing
e: /Workspace/tise-android/app/src/main/java/com/tise/tise/fragments/AddToUDLDialogFragment.kt: (232, 5): 'onViewCreated' overrides nothing
e: /Workspace/tise-android/app/src/main/java/com/tise/tise/fragments/AddToUDLDialogFragment.kt: (233, 29): Type mismatch: inferred type is View? but View was expected
e: /Workspace/tise-android/app/src/main/java/com/tise/tise/fragments/AddToUDLDialogFragment.kt: (243, 86): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type Context?
e: /Workspace/tise-android/app/src/main/java/com/tise/tise/fragments/AddToUDLDialogFragment.kt: (269, 18): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type Bundle?
e: /Workspace/tise-android/app/src/main/java/com/tise/tise/fragments/AttributeValuesListFragment.kt: (61, 33): Type parameter bound for T in val <T : Any> T.javaClass: Class<T>
 is not satisfied: inferred type FragmentActivity? is not a subtype of Any
e: /Workspace/tise-android/app/src/main/java/com/tise/tise/fragments/AttributeValuesListFragment.kt: (61, 43): Type inference failed: Not enough information to infer parameter T in val <T : Any!> Class<T>.simpleName: String!
Please specify it explicitly.

e: /Workspace/tise-android/app/src/main/java/com/tise/tise/fragments/AttributeValuesListFragment.kt: (73, 38): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type Bundle?
e: /Workspace/tise-android/app/src/main/java/com/tise/tise/fragments/BottomBarFragment.kt: (33, 51): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type Context?
e: /Workspace/tise-android/app/src/main/java/com/tise/tise/fragments/BottomBarFragment.kt: (130, 45): Type mismatch: inferred type is Context? but Context was expected
e: /Workspace/tise-android/app/src/main/java/com/tise/tise/fragments/CameraRollFragment.kt: (89, 5): 'onCreateView' overrides nothing
e: /Workspace/tise-android/app/src/main/java/com/tise/tise/fragments/CameraRollFragment.kt: (92, 5): 'onViewCreated' overrides nothing
e: /Workspace/tise-android/app/src/main/java/com/tise/tise/fragments/CameraRollFragment.kt: (93, 29): Type mismatch: inferred type is View? but View was expected
e: /Workspace/tise-android/app/src/main/java/com/tise/tise/fragments/CameraRollFragment.kt: (125, 36): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type FragmentActivity?
e: /Workspace/tise-android/app/src/main/java/com/tise/tise/fragments/SearchFilterFragment.kt: (227, 41): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type Context?
e: /Workspace/tise-android/app/src/main/java/com/tise/tise/fragments/SearchFilterFragment.kt: (230, 16): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type Context?
e: /Workspace/tise-android/app/src/main/java/com/tise/tise/fragments/SearchFilterFragment.kt: (385, 75): Type mismatch: inferred type is Context? but Context was expected
e: /Workspace/tise-android/app/src/main/java/com/tise/tise/fragments/SearchFilterFragment.kt: (385, 103): Type mismatch: inferred type is Context? but Context was expected
e: /Workspace/tise-android/app/src/main/java/com/tise/tise/fragments/SearchFilterFragment.kt: (391, 60): Type mismatch: inferred type is Context? but Context was expected
e: /Workspace/tise-android/app/src/main/java/com/tise/tise/fragments/SearchFilterFragment.kt: (392, 59): Type mismatch: inferred type is Context? but Context was expected
e: /Workspace/tise-android/app/src/main/java/com/tise/tise/fragments/SearchFilterFragment.kt: (542, 24): Expression in a class literal has a nullable type 'FragmentActivity?', use !! to make the type non-nullable
e: /Workspace/tise-android/app/src/main/java/com/tise/tise/fragments/SearchFilterFragment.kt: (558, 5): 'onCreateView' overrides nothing
e: /Workspace/tise-android/app/src/main/java/com/tise/tise/fragments/SearchResultFragment.kt: (59, 25): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type FragmentActivity?
e: /Workspace/tise-android/app/src/main/java/com/tise/tise/fragments/SearchResultFragment.kt: (154, 66): Type mismatch: inferred type is Context? but Context was expected
e: /Workspace/tise-android/app/src/main/java/com/tise/tise/fragments/SearchResultFragment.kt: (158, 82): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type Context?
e: /Workspace/tise-android/app/src/main/java/com/tise/tise/fragments/SearchResultFragment.kt: (170, 41): Type mismatch: inferred type is Context? but Context was expected
e: /Workspace/tise-android/app/src/main/java/com/tise/tise/fragments/SearchResultFragment.kt: (173, 33): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type FragmentActivity?
e: /Workspace/tise-android/app/src/main/java/com/tise/tise/fragments/SectionsListFragment.kt: (102, 37): Type mismatch: inferred type is Context? but Context was expected
e: /Workspace/tise-android/app/src/main/java/com/tise/tise/fragments/SectionsListFragment.kt: (117, 61): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type FragmentActivity?
e: /Workspace/tise-android/app/src/main/java/com/tise/tise/fragments/SectionsListFragment.kt: (119, 56): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type FragmentActivity?
e: /Workspace/tise-android/app/src/main/java/com/tise/tise/fragments/SectionsListFragment.kt: (121, 74): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type Bundle?
e: /Workspace/tise-android/app/src/main/java/com/tise/tise/fragments/SectionsListFragment.kt: (125, 25): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type FragmentActivity?
e: /Workspace/tise-android/app/src/main/java/com/tise/tise/fragments/SectionsListFragment.kt: (130, 25): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type FragmentActivity?
e: /Workspace/tise-android/app/src/main/java/com/tise/tise/fragments/SectionsListFragment.kt: (133, 83): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type FragmentActivity?
e: /Workspace/tise-android/app/src/main/java/com/tise/tise/fragments/SectionsListFragment.kt: (161, 41): Type mismatch: inferred type is Context? but Context was expected
e: /Workspace/tise-android/app/src/main/java/com/tise/tise/fragments/SectionsListFragment.kt: (166, 61): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type FragmentActivity?
e: /Workspace/tise-android/app/src/main/java/com/tise/tise/fragments/SectionsListFragment.kt: (168, 76): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type Bundle?
e: /Workspace/tise-android/app/src/main/java/com/tise/tise/fragments/SectionsListFragment.kt: (172, 25): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type FragmentActivity?
e: /Workspace/tise-android/app/src/main/java/com/tise/tise/fragments/SectionsListFragment.kt: (181, 35): Type mismatch: inferred type is Context? but Context was expected
e: /Workspace/tise-android/app/src/main/java/com/tise/tise/fragments/SectionsListFragment.kt: (182, 84): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type Bundle?
e: /Workspace/tise-android/app/src/main/java/com/tise/tise/fragments/SectionsListFragment.kt: (188, 25): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type FragmentActivity?
e: /Workspace/tise-android/app/src/main/java/com/tise/tise/fragments/SectionsListFragment.kt: (193, 25): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type FragmentActivity?
e: /Workspace/tise-android/app/src/main/java/com/tise/tise/fragments/SectionsListFragment.kt: (216, 17): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type FragmentActivity?
e: /Workspace/tise-android/app/src/main/java/com/tise/tise/fragments/SectionsListFragment.kt: (259, 84): Type mismatch: inferred type is Context? but Context was expected
e: /Workspace/tise-android/app/src/main/java/com/tise/tise/fragments/SectionsListFragment.kt: (260, 89): Type mismatch: inferred type is Context? but Context was expected
e: /Workspace/tise-android/app/src/main/java/com/tise/tise/fragments/SectionsListFragment.kt: (261, 85): Type mismatch: inferred type is Context? but Context was expected
e: /Workspace/tise-android/app/src/main/java/com/tise/tise/fragments/SectionsListFragment.kt: (262, 82): Type mismatch: inferred type is Context? but Context was expected
e: /Workspace/tise-android/app/src/main/java/com/tise/tise/fragments/SectionsListFragment.kt: (267, 63): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type FragmentActivity?
e: /Workspace/tise-android/app/src/main/java/com/tise/tise/fragments/SectionsListFragment.kt: (268, 33): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type FragmentActivity?
e: /Workspace/tise-android/app/src/main/java/com/tise/tise/fragments/SectionsListFragment.kt: (270, 70): Type mismatch: inferred type is Context? but Context was expected
e: /Workspace/tise-android/app/src/main/java/com/tise/tise/fragments/SectionsListFragment.kt: (299, 30): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type Bundle?
e: /Workspace/tise-android/app/src/main/java/com/tise/tise/fragments/SectionsListFragment.kt: (328, 26): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type Bundle?
e: /Workspace/tise-android/app/src/main/java/com/tise/tise/fragments/SectionsListFragment.kt: (340, 45): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type Bundle?
e: /Workspace/tise-android/app/src/main/java/com/tise/tise/fragments/SectionsListFragment.kt: (349, 42): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type Bundle?
e: /Workspace/tise-android/app/src/main/java/com/tise/tise/fragments/SectionsListFragment.kt: (372, 43): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type Bundle?
e: /Workspace/tise-android/app/src/main/java/com/tise/tise/fragments/SectionsListFragment.kt: (396, 24): Expression in a class literal has a nullable type 'FragmentActivity?', use !! to make the type non-nullable
e: /Workspace/tise-android/app/src/main/java/com/tise/tise/fragments/SectionsListFragment.kt: (406, 29): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type FragmentActivity?
e: /Workspace/tise-android/app/src/main/java/com/tise/tise/fragments/SectionsListFragment.kt: (410, 29): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type FragmentActivity?
e: /Workspace/tise-android/app/src/main/java/com/tise/tise/fragments/SectionsListFragment.kt: (422, 5): 'onViewCreated' overrides nothing
e: /Workspace/tise-android/app/src/main/java/com/tise/tise/fragments/SectionsListFragment.kt: (423, 29): Type mismatch: inferred type is View? but View was expected
e: /Workspace/tise-android/app/src/main/java/com/tise/tise/fragments/SectionsListFragment.kt: (479, 66): Type mismatch: inferred type is Context? but Context was expected
e: /Workspace/tise-android/app/src/main/java/com/tise/tise/fragments/SectionsListFragment.kt: (482, 60): Type mismatch: inferred type is Context? but Context was expected
e: /Workspace/tise-android/app/src/main/java/com/tise/tise/fragments/SectionsListFragment.kt: (495, 58): Type mismatch: inferred type is Context? but Context was expected
e: /Workspace/tise-android/app/src/main/java/com/tise/tise/fragments/SectionsListFragment.kt: (496, 68): Type mismatch: inferred type is Context? but Context was expected
e: /Workspace/tise-android/app/src/main/java/com/tise/tise/fragments/SectionsListFragment.kt: (497, 60): Type mismatch: inferred type is Context? but Context was expected
e: /Workspace/tise-android/app/src/main/java/com/tise/tise/fragments/SectionsListFragment.kt: (498, 61): Type mismatch: inferred type is Context? but Context was expected
e: /Workspace/tise-android/app/src/main/java/com/tise/tise/fragments/SectionsListFragment.kt: (508, 64): Type mismatch: inferred type is Context? but Context was expected
e: /Workspace/tise-android/app/src/main/java/com/tise/tise/fragments/SectionsListFragment.kt: (511, 82): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type Context?
e: /Workspace/tise-android/app/src/main/java/com/tise/tise/fragments/StorePagerItemFragment.kt: (76, 17): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type FragmentActivity?
e: /Workspace/tise-android/app/src/main/java/com/tise/tise/fragments/StorePagerItemFragment.kt: (78, 50): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type Bundle?
e: /Workspace/tise-android/app/src/main/java/com/tise/tise/fragments/StorePagerItemFragment.kt: (135, 47): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type FragmentActivity?
e: /Workspace/tise-android/app/src/main/java/com/tise/tise/fragments/StorePagerItemFragment.kt: (143, 52): Type mismatch: inferred type is FragmentActivity? but Context was expected
e: /Workspace/tise-android/app/src/main/java/com/tise/tise/fragments/StorePagerItemFragment.kt: (145, 37): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type FragmentActivity?
e: /Workspace/tise-android/app/src/main/java/com/tise/tise/fragments/StorePagerItemFragment.kt: (274, 70): Smart cast to 'FragmentActivity' is impossible, because 'activity' is a property that has open or custom getter
e: /Workspace/tise-android/app/src/main/java/com/tise/tise/fragments/StorePagerItemFragment.kt: (306, 17): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type FragmentActivity?
e: /Workspace/tise-android/app/src/main/java/com/tise/tise/fragments/StorePagerItemFragment.kt: (312, 81): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type FragmentActivity?
e: /Workspace/tise-android/app/src/main/java/com/tise/tise/fragments/StorePagerItemFragment.kt: (419, 45): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type FragmentActivity?
e: /Workspace/tise-android/app/src/main/java/com/tise/tise/fragments/UDLOptionsDialogFragment.kt: (48, 33): Expression in a class literal has a nullable type 'FragmentActivity?', use !! to make the type non-nullable
e: /Workspace/tise-android/app/src/main/java/com/tise/tise/fragments/UDLOptionsDialogFragment.kt: (55, 5): 'onViewCreated' overrides nothing
e: /Workspace/tise-android/app/src/main/java/com/tise/tise/fragments/UDLOptionsDialogFragment.kt: (56, 29): Type mismatch: inferred type is View? but View was expected
e: /Workspace/tise-android/app/src/main/java/com/tise/tise/fragments/UDLOptionsDialogFragment.kt: (57, 33): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type Bundle?

:app:compileDebugKotlin FAILED
:app:buildInfoGeneratorDebug

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugKotlin'.
> Compilation error. See log for more details
`

**Comment by iftekhar-ahmed** [comment]
@froesmatheus I ended up ditching the library. Later discovered the library had nothing to do with the kotlin errors. Google on some appcompat version update, decided all getContext(), getActivity() calls are candidates for null return types and kotlin compiler just put the icing on the cake(!). That's why so many errors showed up. You gotta put the Force RTE !! or check nulls with elvis ?: here
